#(C) Copyright 2019-2022 Hewlett Packard Enterprise Development LP

run:
  deadline: 240s
  tests: true
  skip-dirs:
    - vendor
  build-tags: acceptance

linters-settings:
  dupl:
    threshold: 110
  lll:
    line-length: 128
  goimports:
    local-prefixes: "github.com/HPE"
  godox:
    keywords:
      - OPTIMIZE
  exhaustive:
    default-signifies-exhaustive: true
  funlen:
    lines: 90
    statements: 60
  depguard:
    rules:
      Main:
        allow:
          - $gostd
          - github.com/hashicorp/terraform-plugin-go
          - github.com/hashicorp/terraform-plugin-mux
          - github.com/hashicorp/terraform-plugin-sdk
          - github.com/HPE/terraform-provider-hpegl
          - github.com/hewlettpackard/hpegl-provider-lib
          - github.com/hewlettpackard/hpegl-metal-terraform-resources
          - github.com/HewlettPackard/hpegl-containers-terraform-resources
          - github.com/HewlettPackard/hpegl-vmaas-terraform-resources

linters:
  enable-all: true
  disable:
    - wsl
    - gci
    - goerr113
    - godot
    - gomnd
    - gochecknoinits
    - gochecknoglobals
    - exhaustivestruct
    - forbidigo
    - testpackage
    - nolintlint
    - varnamelen
    # Temporarily disabling paralleltest
    - paralleltest
    #Temporarily disabling wrapcheck
    - wrapcheck
    - staticcheck
    # Disable the 'cyclop' cyclometric complexity linter. 'gocyclo' already
    # covers cyclometric complexity, and 'cyclop' has no documentation to 
    # help with resolving the flagged lints
    # - cyclop

issues:

  exclude-rules:
    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "

    # ignore function length for tests as look up tables typically exceed.
    - linters:
        - funlen
        - goerr113
      path: _test\.go

    - linters:
        - dupl
      path: ".*generated.*go"

    - linters:
        - goconst
      path: ".*generated.*go"

    - linters:
        - staticcheck
      text: "SA9003:"

    - linters:
        - stylecheck
      text: "ST1005:"

  max-same-issues: 0
