name: Acceptance Test Caas

on:
  schedule:
    # Runs every night at 1:30 am
    - cron: "15 15 * * *"
env: 
  HPEGL_IAM_SERVICE_URL: ${{ secrets.CAAS_HPEGL_IAM_SERVICE_URL }}
  HPEGL_TENANT_ID: ${{ secrets.CAAS_HPEGL_TENANT_ID }}
  HPEGL_USER_SECRET: ${{ secrets.CAAS_HPEGL_USER_SECRET }}
  HPEGL_USER_ID: ${{ secrets.CAAS_HPEGL_USER_ID }}
jobs:
  ci:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [ '1.17' ]
    name: Acceptance Tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: go install github.com/nomad-software/vend@v1.0.3
      - run: make acceptance-caas
