name: Acceptance Test Caas

on:
  schedule:
    # Runs every night at 1:30 am
    - cron: "30 1 * * *"
env:
  HPEGL_TENANT_ID: ${{ secrets.CAAS_HPEGL_TENANT_ID }}
  TF_VAR_HPEGL_SPACE: ${{ secrets.CAAS_TF_VAR_HPEGL_SPACE }}
  HPEGL_USER_ID: ${{ secrets.CAAS_HPEGL_USER_ID }}
  HPEGL_USER_SECRET: ${{ secrets.CAAS_HPEGL_USER_SECRET }}
  HPEGL_API_VENDED_SERVICE_CLIENT: ${{ secrets.CAAS_HPEGL_API_VENDED_SERVICE_CLIENT }}
  HPEGL_IAM_SERVICE_URL: ${{ secrets.CAAS_HPEGL_IAM_SERVICE_URL }}
jobs:
  ci:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [ '1.20' ]
    name: Acceptance Tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - run: go install github.com/nomad-software/vend@v1.0.3
      - run: make acceptance-caas
