name: GitHub Actions CI

on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [ '1.19' ]
    name: Linting
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - run: make lint
