name: GitHub Actions CI

on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        go: [ '1.24.1' ]
    name: Linting
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - run: make lint
